In [4]:
import numpy as np
import pandas as pd

In [ ]:
# komenda shellowa w jupyter notebook
!dir

 Volume in drive C is OS
 Volume Serial Number is 889C-56B7

 Directory of c:\Users\lemur\Desktop\sages-pandas\szkolenie_pandas-2026_09_28-2026_09_30\robocze

28.09.2026  09:44    <DIR>          .
27.09.2026  18:19    <DIR>          ..
28.09.2026  09:40             1�517 00_poczatek.ipynb
28.09.2026  09:46             1�167 01_pakiety_numpy.ipynb
               2 File(s)          2�684 bytes
               2 Dir(s)  122�624�663�552 bytes free


In [ ]:
# instalacja pakietów numpy i pandas z poziomu jupyter notebook
!pip install numpy pandas


[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: C:\Users\lemur\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip


In [ ]:
# użycie numpy

In [6]:
lista = [1,2,3,4,2,3,4,5]

# czy liczba jest parzysta?
for element in lista:
    if element >= 3:
        print(f"{element} jest >=3 ")
    else:
        print(f"{element} jest < 3")

1 jest < 3
2 jest < 3
3 jest >=3 
4 jest >=3 
2 jest < 3
3 jest >=3 
4 jest >=3 
5 jest >=3 


In [12]:
lista

[1, 2, 3, 4, 2, 3, 4, 5]

In [14]:
np_lista = np.array(lista)
np.where(np_lista >= 3, ">= 3", "< 3")

array(['< 3', '< 3', '>= 3', '>= 3', '< 3', '>= 3', '>= 3', '>= 3'],
      dtype='<U4')

In [11]:
np_lista


array([1, 2, 3, 4, 2, 3, 4, 5])

In [ ]:
np.where(np_lista % 2, "parzyste", "nieparzyste")

array(['parzyste', 'nieparzyste', 'parzyste', 'nieparzyste',
       'nieparzyste', 'parzyste', 'nieparzyste', 'parzyste'], dtype='<U11')

In [16]:
zarobki = np.array(  [3500, 7250, 12500, 4800, 9100 ]  )


In [17]:
np.where(zarobki > 8000, "drugi próg", "pierwszy próg")

array(['pierwszy próg', 'pierwszy próg', 'drugi próg', 'pierwszy próg',
       'drugi próg'], dtype='<U13')

In [ ]:
warunki = [
    zarobki < 5000,
    (zarobki >= 5000) & (zarobki < 10000),
    zarobki >= 10000
]
etykiety = ['junior', 'mid', 'senior']

In [24]:
warunki


[array([False,  True, False, ..., False, False, False], shape=(1000000,)),
 array([False, False, False, ...,  True,  True, False], shape=(1000000,)),
 array([ True, False,  True, ..., False, False,  True], shape=(1000000,))]

In [19]:
np.select( warunki, etykiety, default="nieznany" )

array(['junior', 'mid', 'senior', 'junior', 'mid'], dtype='<U8')

In [22]:
zarobki = np.random.normal(10000, 5000, size=1_000_000)
warunki = [zarobki < 5000, (zarobki >= 5000) & (zarobki < 10000), zarobki >= 10000]
etykiety = ["junior", "mid", "senior"]

In [23]:
np.select(warunki, etykiety, default="nieznany")


array(['senior', 'junior', 'senior', ..., 'mid', 'mid', 'senior'],
      shape=(1000000,), dtype='<U8')

In [28]:
zarobki = np.array([3500, 7250, 12500, 4800, 9100])
warunki = [
    zarobki > 3000,
    zarobki < 5000,
    (zarobki >= 5000) & (zarobki < 10000),
    zarobki >= 10000,
]
etykiety = ["junior","junior2", "mid", "senior"]
np.select(warunki, etykiety, default="nieznany")


array(['junior', 'junior', 'junior', 'junior', 'junior'], dtype='<U8')

In [29]:
warunki

[array([ True,  True,  True,  True,  True]),
 array([ True, False, False,  True, False]),
 array([False,  True, False, False,  True]),
 array([False, False,  True, False, False])]

In [ ]:
if l >= 2:
    ...
elif l >= 1:
    ...
else:
    ...

In [30]:
import pandas as pd

In [35]:
pd.Series([3500, 7250, 12500, 4800, 9100])

0     3500
1     7250
2    12500
3     4800
4     9100
dtype: int64

In [34]:
pd.Series([3500, "7250", 12500, 4800, 9100])


0     3500
1     7250
2    12500
3     4800
4     9100
dtype: object

In [36]:
seria = pd.Series([3500, 7250, 12500, 4800, 9100])
seria


0     3500
1     7250
2    12500
3     4800
4     9100
dtype: int64

In [37]:
seria[3]

np.int64(4800)

In [38]:
# index
seria = pd.Series([3500, 7250, 12500, 4800, 9100], index=['jeden', 'dwa', 'trzy', 'cztery', 'pięć'])
seria

jeden      3500
dwa        7250
trzy      12500
cztery     4800
pięć       9100
dtype: int64

In [39]:
seria['trzy']

np.int64(12500)

In [41]:
seria.cztery

np.int64(4800)